version: "3.8"

services:
  mysql_db:
    container_name: mysql_db
    image: mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elhmel
    ports:
      - "3307:3306"
    restart: on-failure

  elhmel_app:
    container_name: elhmel_app
    build:
      context: ./
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - mysql_db
    restart: on-failure
