version: '3'
services:
  db:
    image: mysql:latest
    container_name: mysql-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: elhmel
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    ports:
      - "3306:3306"
    restart: always

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: 'elhmel-site'
    ports:
      - 8080:8080
    environment:
      MYSQL_HOST: db
    restart: always
    links:
      - db
