spring:
  datasource:
    username: root
    url: jdbc:mysql://mysql_db:3306/elhmel
    driverClassName: com.mysql.jdbc.Driver
    password: root
  jpa:
    generate-ddl: 'true'
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        show_sql: 'true'
  security:
    oauth2:
      client:
        registration:
          google:
            client-secret: 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
            client-id: 1011803130587-1kqkgo0l9cb72rhs7hbj812rf9knnvc4.apps.googleusercontent.com
server:
  port: 8080
